jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Caso | abierto ${{ github.event.issue.number }}"
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: ...
  test:
    needs:build
    runs-on: ubuntu-latest
    steps:
      - run: ...
